/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package responderEncuesta;

import encuesta.MensajeDialog;
import encuesta.SeleccionPrograma;
import static encuesta.SeleccionPrograma.PASSWORD;
import static encuesta.SeleccionPrograma.URL;
import static encuesta.SeleccionPrograma.USERNAME;
import java.awt.Color;
import java.awt.Dimension;
import javax.swing.BorderFactory;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.JRadioButton;

public class ListaPreguntas extends javax.swing.JFrame {
    
    String idencuesta, titulo, descripcion;
    int preguntaY = 15;
    ArrayList<PanelPreguntaRespuesta> listaPanelesPregunta = new ArrayList<>();

    public ListaPreguntas(String idencuesta, String titulo, String descripcion) {
        this.idencuesta = idencuesta;
        this.titulo = titulo;
        this.descripcion = descripcion;
        setTitle("Responder a " + this.titulo);
        setResizable(false);
        initComponents();
    }

    private ListaPreguntas() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("CANCELAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("ENVIAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 102, 255), 2, true));
        jPanel2.setForeground(new java.awt.Color(255, 229, 122));

        jLabel1.setText(descripcion);

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        jLabel2.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, new Color(51,102,255)));
        jLabel2.setText(titulo);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1020, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jScrollPane1.setHorizontalScrollBar(null);

        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 2, true));
        jPanel3.setPreferredSize(new java.awt.Dimension(1055, 15));
        jPanel3.setLayout(null);

        try (Connection conexion = DriverManager.getConnection(URL, USERNAME, PASSWORD)) {
            // Consulta SQL parametrizada
            String sql = "SELECT numeroPregunta, idencuesta, texto, tipo_respuesta, opciones FROM pregunta WHERE idencuesta = ?";

            // Crear el PreparedStatement
            try (PreparedStatement statement = conexion.prepareStatement(sql)) {
                // Establecer el valor del parámetro
                statement.setString(1, idencuesta);

                // Ejecutar la consulta
                try (ResultSet resultSet = statement.executeQuery()) {
                    while (resultSet.next()) {
                        // Obtener los valores de cada columna

                        int numeroPregunta = resultSet.getInt("numeroPregunta");
                        int idEncuesta = resultSet.getInt("idencuesta");
                        String texto = resultSet.getString("texto");
                        String tipoRespuesta = resultSet.getString("tipo_respuesta");
                        String opciones = resultSet.getString("opciones");

                        PanelPreguntaRespuesta pregunta = new PanelPreguntaRespuesta(numeroPregunta, texto, tipoRespuesta, opciones, preguntaY);
                        listaPanelesPregunta.add(pregunta);
                        int posYaAumentar = pregunta.getHeight() + 15;

                        pregunta.setVisible(true);
                        jPanel3.add(pregunta);
                        jPanel3.repaint();
                        jPanel3.revalidate();
                        preguntaY = preguntaY + pregunta.getHeight() + 15;

                        jPanel3.setPreferredSize(new Dimension(1055, jPanel3.getPreferredSize().height + posYaAumentar));
                    }
                }
            }

        } catch (SQLException e) {
            System.err.println("Error al conectar a la base de datos: " + e.getMessage());
        }

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1055, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 504, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jPanel3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1055, Short.MAX_VALUE))
                .addGap(25, 25, 25))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        SeleccionPrograma ventanaInicial = new SeleccionPrograma();
        ventanaInicial.setLocationRelativeTo(null);
        ventanaInicial.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        String consultaSQL = "INSERT INTO respuestas (encuestaID, numeroPregunta, texto_respuesta) VALUES (?, ?, ?)";
        
        try (
            // Establecer la conexión con la base de datos
            Connection conexion = DriverManager.getConnection(URL, USERNAME, PASSWORD);

            // Crear el PreparedStatement con la consulta SQL
            PreparedStatement declaracion = conexion.prepareStatement(consultaSQL)
        ) {
            // Establecer los valores de los parámetros
            boolean algunaInsercionFallida = false;
            for(PanelPreguntaRespuesta respuesta : listaPanelesPregunta) {
                declaracion.setInt(1, Integer.parseInt(this.idencuesta));
                declaracion.setInt(2, respuesta.numeroPregunta); 
                if(respuesta.tipo_respuesta.equals("Texto")) {
                    declaracion.setString(3, respuesta.campoRespuesta.getText());  
                } else {
                    for(JRadioButton opc : respuesta.opcionesArray) {
                        if(opc.isSelected()) {
                            declaracion.setString(3, opc.getText());
                            break;
                        }
                    }
                }
              
                // Ejecutar la consulta
                int filasAfectadas = declaracion.executeUpdate();
                if (filasAfectadas <= 0) {
                    // Fallo al insertar en la segunda tabla
                    algunaInsercionFallida = true;
                    break;  // Salir del bucle
                }
            }
            if (algunaInsercionFallida) {
                // Lógica para manejar inserciones fallidas en la segunda tabla
                MensajeDialog preguntasNoCreadas = new MensajeDialog(this, true, "No se pudieron enviar las respuestas");
                preguntasNoCreadas.setLocationRelativeTo(null);
                preguntasNoCreadas.setVisible(true);
                this.dispose();
                SeleccionPrograma ventanaInicial = new SeleccionPrograma();
                ventanaInicial.setLocationRelativeTo(null);
                ventanaInicial.setVisible(true);
            } else {
                // Éxito al insertar en ambas tablas
                MensajeDialog formularioCreado = new MensajeDialog(this, true, "Las respuestas se enviaron con éxito");
                formularioCreado.setLocationRelativeTo(null);
                formularioCreado.setVisible(true);
                this.dispose();
                SeleccionPrograma ventanaInicial = new SeleccionPrograma();
                ventanaInicial.setLocationRelativeTo(null);
                ventanaInicial.setVisible(true);
            }
            
            
        } catch (SQLException e) {
            // Manejar cualquier excepción de SQL
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaPreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaPreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaPreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaPreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaPreguntas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
