/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package encuesta;

import administrarEncuesta.VerRespuestas;
import com.formdev.flatlaf.themes.FlatMacDarkLaf;
import creacionEncuesta.Crearencuesta;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import responderEncuesta.ListaPreguntas;

public class SeleccionPrograma extends javax.swing.JFrame {
    
    // Datos de conexion de la base de datos
    public static final String URL = "";
    public static final String USERNAME = "";
    public static final String PASSWORD = "";

    
    public SeleccionPrograma() {
        FlatMacDarkLaf.setup();
        setTitle("SuervyMaster");
        setResizable(false);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("RESPONDER UNA ENCUESTA");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 330, 45));

        jButton2.setText("CREAR UNA ENCUESTA");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 330, 45));

        jButton3.setText("ADMINISTRAR UNA ENCUESTA EXISTENTE");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 305, 330, 45));

        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 2, true));
        jPanel2.setForeground(new java.awt.Color(250, 250, 250));
        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 65, 75));
        jPanel2.add(jLabel2);
        jLabel2.setBounds(160, 50, 160, 17);

        jLabel3.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 65, 75));
        jPanel2.add(jLabel3);
        jLabel3.setBounds(160, 150, 160, 17);
        jPanel2.add(jTextField1);
        jTextField1.setBounds(20, 50, 130, 25);
        jPanel2.add(jPasswordField1);
        jPasswordField1.setBounds(20, 150, 130, 25);

        jLabel4.setText("Código de encuesta:");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(20, 20, 170, 19);

        jLabel5.setText("Contraseña de la encuesta:");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(20, 110, 170, 19);

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 230, 340, 200));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/encuesta/Logo.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 720, 190));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 810, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(jTextField1.getText().isBlank()) {
            jLabel2.setText("¡Este campo es necesario!");
            jLabel3.setText("");
        } else {
            jLabel2.setText("");
            jLabel3.setText("");
            try (Connection conexion = DriverManager.getConnection(URL, USERNAME, PASSWORD)) {
                // Consulta SQL parametrizada
                String sql = "SELECT idencuesta, titulo, descripcion FROM encuesta WHERE idencuesta = ?";

                // Crear el PreparedStatement
                try (PreparedStatement statement = conexion.prepareStatement(sql)) {
                    // Establecer el valor del parámetro
                    statement.setString(1, jTextField1.getText());

                    // Ejecutar la consulta
                    try (ResultSet resultSet = statement.executeQuery()) {
                        if (resultSet.next()) {
                            // Hay al menos una coincidencia
                            // Puedes acceder a los datos del resultado aquí si es necesario
                            this.dispose();
                            ListaPreguntas encuestaAResponder = new ListaPreguntas(jTextField1.getText(), resultSet.getString("titulo"), resultSet.getString("descripcion"));
                            encuestaAResponder.setLocationRelativeTo(null);
                            encuestaAResponder.setVisible(true);
                        } else {
                            // No hay coincidencias
                            MensajeDialog mensajeError = new MensajeDialog(this, true, "No existe una encuesta con ese código");
                            mensajeError.setLocationRelativeTo(null);
                            mensajeError.setVisible(true);
                        }
                    }
                }

            } catch (SQLException e) {
                System.err.println("Error al conectar a la base de datos: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        if(!jTextField1.getText().isBlank() && !new String(jPasswordField1.getPassword()).isBlank()) {
            jLabel2.setText("");
            jLabel3.setText("");
            try (Connection conexion = DriverManager.getConnection(URL, USERNAME, PASSWORD)) {
                // Consulta SQL parametrizada
                String sql = "SELECT idencuesta, contraseña, titulo, descripcion FROM encuesta WHERE idencuesta = ?";

                // Crear el PreparedStatement
                try (PreparedStatement statement = conexion.prepareStatement(sql)) {
                    // Establecer el valor del parámetro
                    statement.setString(1, jTextField1.getText());

                    // Ejecutar la consulta
                    try (ResultSet resultSet = statement.executeQuery()) {
                        if (resultSet.next()) {
                            // Hay al menos una coincidencia
                            String codigoEncuesta = resultSet.getString("idencuesta");
                            String contraseñaEncuesta = resultSet.getString("contraseña");
                            String titulo = resultSet.getString("titulo");
                            String descripcion = resultSet.getString("descripcion");

                            // Verificar la contraseña
                            if (contraseñaEncuesta.equals(new String(jPasswordField1.getPassword()))) {
                                // La contraseña coincide, realiza la acción deseada
                                VerRespuestas ventanaAnalisis = new VerRespuestas(codigoEncuesta, titulo, descripcion);
                                ventanaAnalisis.setLocationRelativeTo(null);
                                ventanaAnalisis.setVisible(true);
                                this.dispose();

                            } else {
                                // La contraseña no coincide
                                jPasswordField1.setText("");
                                MensajeDialog mensajeError = new MensajeDialog(this, true, "La contraseña de la encuesta no es válida");
                                mensajeError.setLocationRelativeTo(null);
                                mensajeError.setVisible(true);
                            }
                        } else {
                            // No hay coincidencias
                            MensajeDialog mensajeError = new MensajeDialog(this, true, "No existe una encuesta con ese código");
                            mensajeError.setLocationRelativeTo(null);
                            mensajeError.setVisible(true);
                        }
                    }
                }
            } catch (SQLException e) {
                System.err.println("Error al conectar a la base de datos: " + e.getMessage());
            }
        } else {
            jLabel2.setText(jTextField1.getText().isBlank() ? "¡Este campo es necesario!" : "");
            jLabel3.setText(new String(jPasswordField1.getPassword()).isBlank() ? "¡Este campo es necesario!" : "");
        }    
       
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Crearencuesta ventanaCrearEncuesta = new Crearencuesta();
        ventanaCrearEncuesta.setLocationRelativeTo(null);
        ventanaCrearEncuesta.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SeleccionPrograma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SeleccionPrograma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SeleccionPrograma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SeleccionPrograma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SeleccionPrograma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
